### ISSUE TITLE
Schema type assignment when the Scale is null is breaking

### ISSUE THREAD

**Issue by kaynancl** [thake/logminer-kafka-connect#2]
Hi Thorsten,
You did a great job in developing this kafka connector that can work with Oracle LogMiner. I have been trying to use it to create CDC from the Oracle databases we used at work.

A small example of what I want to report here, is happening with one of the tables that I have to monitor.

Table:
```sql
create table EVENTLOG
(
    ID              NUMBER(38) not null primary key,
    LATITUDE        NUMBER default 0,
    LONGITUDE       NUMBER default 0,
    CLOSED          NUMBER(1)  not null,
    WHENRECHECK     DATE
)
```

When the toSchemaType method is called to
the LATITUDE and LONGITUDE columns, the value NumberType.BigDecimalType (0) is being assigned.

Although these columns have their default value set to 0, the actual value that these columns can receive are, for example, 30.516658782958984, -89.65824127197266 and 27.4935367.

Therefore, during the execution of the connector, I have received the following exception:

```log
[2020-04-03 12:33:20,353] INFO Oracle Kafka Connector is starting (com.github.thake.logminer.kafka.connect.SourceTask:189)
[2020-04-03 12:33:21,541] INFO Connected to database at localhost:1521/XE (com.github.thake.logminer.kafka.connect.SourceTask:30)
[2020-04-03 12:33:21,542] INFO WorkerSourceTask{id=oracle-cdc-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:209)
[2020-04-03 12:33:21,708] INFO Determined current scn of database as 545994 (com.github.thake.logminer.kafka.connect.initial.SelectSource:50)
[2020-04-03 12:33:21,709] INFO Getting dictionary details for table : TableId(owner=GREENMILE, table=EVENTLOG) (com.github.thake.logminer.kafka.connect.SchemaService:39)
[2020-04-03 12:33:21,756] INFO ID | Scale: 0 | Precision: 38 (com.github.thake.logminer.kafka.connect.ColumnSchemaBuilder:151)
[2020-04-03 12:33:21,759] INFO NumberType.BigDecimalType (com.github.thake.logminer.kafka.connect.ColumnSchemaBuilder:203)
[2020-04-03 12:33:21,836] INFO LATITUDE | Scale: null | Precision: 0 (com.github.thake.logminer.kafka.connect.ColumnSchemaBuilder:151)
[2020-04-03 12:33:21,837] INFO Scale null: NumberType.BigDecimalType(0) (com.github.thake.logminer.kafka.connect.ColumnSchemaBuilder:165)
[2020-04-03 12:33:21,840] INFO LONGITUDE | Scale: null | Precision: 0 (com.github.thake.logminer.kafka.connect.ColumnSchemaBuilder:151)
[2020-04-03 12:33:21,840] INFO Scale null: NumberType.BigDecimalType(0) (com.github.thake.logminer.kafka.connect.ColumnSchemaBuilder:165)
[2020-04-03 12:33:21,843] INFO CLOSED | Scale: 0 | Precision: 1 (com.github.thake.logminer.kafka.connect.ColumnSchemaBuilder:151)
[2020-04-03 12:33:21,844] INFO NumberType.ByteType (com.github.thake.logminer.kafka.connect.ColumnSchemaBuilder:185)
[2020-04-03 12:33:21,846] INFO WHENRECHECK | Scale: null | Precision: 0 (com.github.thake.logminer.kafka.connect.ColumnSchemaBuilder:151)
[2020-04-03 12:33:21,846] INFO TimeType.DateType (com.github.thake.logminer.kafka.connect.ColumnSchemaBuilder:210)
[2020-04-03 12:33:30,316] INFO WorkerSourceTask{id=oracle-cdc-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:416)
[2020-04-03 12:33:30,319] INFO WorkerSourceTask{id=oracle-cdc-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:433)
[2020-04-03 12:33:40,320] INFO WorkerSourceTask{id=oracle-cdc-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:416)
[2020-04-03 12:33:40,320] INFO WorkerSourceTask{id=oracle-cdc-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:433)
[2020-04-03 12:33:50,323] INFO WorkerSourceTask{id=oracle-cdc-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:416)
[2020-04-03 12:33:50,324] INFO WorkerSourceTask{id=oracle-cdc-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:433)
[2020-04-03 12:34:00,328] INFO WorkerSourceTask{id=oracle-cdc-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:416)
[2020-04-03 12:34:00,329] INFO WorkerSourceTask{id=oracle-cdc-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:433)
[2020-04-03 12:34:01,928] INFO Found 1000 new changes. Submitting them to kafka. (com.github.thake.logminer.kafka.connect.SourceTask:161)
[2020-04-03 12:34:01,935] INFO WorkerSourceTask{id=oracle-cdc-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:416)
[2020-04-03 12:34:01,935] INFO WorkerSourceTask{id=oracle-cdc-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:433)
[2020-04-03 12:34:01,936] ERROR WorkerSourceTask{id=oracle-cdc-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:290)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:316)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:240)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: BigDecimal has mismatching scale value for given Decimal schema
	at org.apache.kafka.connect.data.Decimal.fromLogical(Decimal.java:68)
	at org.apache.kafka.connect.json.JsonConverter$13.toJson(JsonConverter.java:206)
	at org.apache.kafka.connect.json.JsonConverter.convertToJson(JsonConverter.java:606)
	at org.apache.kafka.connect.json.JsonConverter.convertToJson(JsonConverter.java:693)
	at org.apache.kafka.connect.json.JsonConverter.convertToJson(JsonConverter.java:693)
	at org.apache.kafka.connect.json.JsonConverter.convertToJsonWithEnvelope(JsonConverter.java:581)
	at org.apache.kafka.connect.json.JsonConverter.fromConnectData(JsonConverter.java:335)
	at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:62)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$2(WorkerSourceTask.java:290)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
	... 11 more
[2020-04-03 12:34:01,938] ERROR WorkerSourceTask{id=oracle-cdc-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)
[2020-04-03 12:34:01,938] INFO Stop called for logminer (com.github.thake.logminer.kafka.connect.SourceTask:213)
[2020-04-03 12:34:01,939] INFO Kafka connect oracle task will be stopped (com.github.thake.logminer.kafka.connect.SourceTask:167)
[2020-04-03 12:34:01,944] INFO Stopped logminer (com.github.thake.logminer.kafka.connect.SourceTask:216)
```

Following the data typing recommendation in the [ALL_TAB_COLUMNS](https://docs.oracle.com/cd/B19306_01/server.102/b14237/statviews_2094.htm) documentation , which by definition has:
DATA_PRECISION = Decimal precision for NUMBER datatype; binary precision for FLOAT datatype, null for all other datatypes.

In the case of zero scale and precision 0, would the correct data type be Float? Have you experienced this problem?

**Comment by thake** [comment]
I've not yet experienced this issue. I'm working on a test case to reproduce it in my dev environment. Thanks for reporting this issue!

**Comment by thake** [comment]
Finding it hard to reproduce. Can you push a testcase that fails?

**Comment by thake** [comment]
Should be fixed with next version.
