### ISSUE TITLE
Error  "No enum constant"

### ISSUE THREAD

**Issue by guschinaglia** [thake/logminer-kafka-connect#6]
Hello,

i'm getting the following error when executing the connector:

[2020-10-20 10:53:06,456] ERROR WorkerSourceTask{id=logminer-kafka-connect-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:187)
java.lang.IllegalArgumentException: No enum constant com.github.thake.logminer.kafka.connect.Operation.DIRECT INSERT
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.github.thake.logminer.kafka.connect.Operation.valueOf(Operation.kt)
	at com.github.thake.logminer.kafka.connect.logminer.LogminerFetcher.extractChange(LogminerFetcher.kt:124)
	at com.github.thake.logminer.kafka.connect.logminer.LogminerFetcher.extractRow(LogminerFetcher.kt:114)
	at com.github.thake.logminer.kafka.connect.logminer.LogminerFetcher.nextRow(LogminerFetcher.kt:69)
	at com.github.thake.logminer.kafka.connect.logminer.LogminerSource$QueryStartedState.processNextLogminerRow(LogminerSource.kt:97)
	at com.github.thake.logminer.kafka.connect.logminer.LogminerSource$QueryStartedState.poll(LogminerSource.kt:85)
	at com.github.thake.logminer.kafka.connect.logminer.LogminerSource.poll(LogminerSource.kt:51)
	at com.github.thake.logminer.kafka.connect.StartedState$poll$2.invoke(SourceTask.kt:134)
	at com.github.thake.logminer.kafka.connect.StartedState.poll(SourceTask.kt:146)
	at com.github.thake.logminer.kafka.connect.SourceTask.poll(SourceTask.kt:206)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:289)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:256)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-10-20 10:53:06,456] ERROR WorkerSourceTask{id=logminer-kafka-connect-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:188)

I Did check the distinct Operation in my Database:
SELECT distinct(operation) FROM V$LOGMNR_CONTENTS 

result: 
START
COMMIT
ROLLBACK
UPDATE
INTERNAL
INSERT

I did fork it but couldn't find how to execute it on Intellij Idea or how to debug it. There is no Gradle run config.
Can you please add a "how to"?

Thank you

**Comment by thake** [comment]
@guschinaglia Thanks for your bug report! 

I'm a little bit confused why the operation returned from V$LOGMNR_CONTENTS is "DIRECT INSERT". Can you tell me which Oracle version you are using? Are you sure, that the logfiles in the logminer session used for your query `SELECT distinct(operation) FROM V$LOGMNR_CONTENTS` are the same as in the logminer kafka connect session that threw the exception? The newest version will log the monitored logfiles if on DEBUG level.

It would be even better if you can contribute a unit test to reproduce the problem. You'll find a couple of unit tests that spin up a temporary oracle 11.2 instance (using docker). Have a look at LongStatementsTest. 

Right now there is no standalone way to execute it within Intellij against a live database. Could you raise a new issue for this? Thanks!

**Comment by guschinaglia** [comment]
@thake 
For now, i'm using Oracle Database 12c Enterprise Edition Docker, available officially from Oracle. 
[Oracle Docker](https://hub.docker.com/_/oracle-database-enterprise-edition)

I'll check the session again and also try to make a unit test.

Thanks !

**Comment by thake** [comment]
@guschinaglia 
Have you been successfully reproducing the issue in a unit test?

**Comment by guschinaglia** [comment]
Hello @thake 
Sorry, i couldn't yet make the unit test.

**Comment by guschinaglia** [comment]
Hello @thake 
I did recreated my environment using now Oracle XE for testing and doesn't show this error anymore. I Have created a different issue for this. #10
